version: "3"

services:
        points:
                ports:
                        - "3000:3000"
                build:
                        context: .
                        dockerfile: Dockerfile
                environment:
                        ENV_NAME: production
